export { default as AddTeamPopup } from "./AddTeamPopup";
export { default as DeleteTeamPopup } from "./DeleteTeamPopup";
export { default as EditTeamPopup } from "./EditTeamPopup";
export { default as AddPlayerPopup } from './AddPlayerPopup'
export { default as EditPlayerPopup } from './EditPlayerPopup'
export { default as DeletePlayerPopup } from './DeletePlayerPopup'
export { default as AddRoundPopup } from './AddRoundPopup'
export { default as DeleteRoundPopup } from './DeleteRoundPopup'
export { default as EditRoundPopup } from './EditRoundPopup'
export { default as AddMatchPopup } from './AddMatchPopup'
export { default as AddPlayerToLinupPopup } from './AddPlayerToLinupPopup'
export { default as DeletePlayerFromLinupPopup } from './DeletePlayerFromLinupPopup'
export { default as EditPlayerLinupPopup } from './EditPlayerLinupPopup'
export { default as PlayerStatsPopup } from './PlayerStatsPopup'
